id: I34A76DBC
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T11:58:26+00:00'
last_modified: '2022-06-08T10:44:40.990596+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00KG01654
  title: ཐོག་མའི་བསྐུར་ཡིག་དང་ལོག་པར་སྨྲ་བ་ཚར་གཅོད་པའི་རལ་གྲི་རྣོ་ངར་འབུམ་ལྡན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    A7A1:
      image_group_id: I00KG02967
      title: ''
      total_pages: 82
      order: 1
      base_file: A7A1.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
